package com.superapp.transaction.payment.dto;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "Payment intent value generated by provider")
public record PaymentIntentDto(
        @Schema(description = "Intent mechanism type", example = "UPI")
        String type,

        @Schema(description = "Intent payload, deep link URL, or checkout token", example = "upi://pay?pa=superapp@icici&...")
        String value
) {}
