services:
  postgres:
    image: postgis/postgis:16-3.4-alpine
    container_name: superapp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: superappdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d superappdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2-alpine
    container_name: superapp-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailpit:
    image: axllent/mailpit:latest
    container_name: superapp-mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: superapp-backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      PORT: 8080
      SERVER_ADDRESS: 0.0.0.0
      DB_URL: jdbc:postgresql://postgres:5432/superappdb
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: 6A576E5A7234753778214125442A472D4B6150645367566B5970337336763979
      JWT_ISSUER: superapp-api
      JWT_AUDIENCE: superapp-client
      CORS_ALLOWED_ORIGINS: http://localhost:3000,http://localhost:5173
      MAIL_MOCK: "true"
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
      LOG_LEVEL_APP: INFO
    ports:
      - "8080:8080"

volumes:
  postgres_data:
  redis_data:
