package com.superapp.common.response;

/**
 * Machine-readable error codes for all application exceptions.
 * Frontend and mobile apps should use these codes for localization.
 */
public enum ApiError {
    // Auth
    INVALID_CREDENTIALS,
    INVALID_OTP,
    INVALID_TOKEN,
    ACCOUNT_BLOCKED,
    ACCOUNT_INACTIVE,
    TOKEN_EXPIRED,
    TOKEN_INVALID,
    TOKEN_REVOKED,
    TOKEN_REUSE_DETECTED,
    UNAUTHORIZED,
    FORBIDDEN,
    REFRESH_TOKEN_INVALID,

    // Registration / User / Merchant / Store / Category / Location
    EMAIL_ALREADY_EXISTS,
    MOBILE_ALREADY_EXISTS,
    USER_NOT_FOUND,
    USER_SUSPENDED,
    SESSION_NOT_FOUND,
    MERCHANT_NOT_FOUND,
    MERCHANT_ACCESS_DENIED,
    INVALID_MERCHANT_STATE,
    STORE_NOT_FOUND,
    STORE_ACCESS_DENIED,
    INVALID_LOCATION,
    INVALID_STORE_STATE,
    CITY_NOT_FOUND,
    CITY_INACTIVE,
    CITY_ALREADY_EXISTS,
    CATEGORY_NOT_FOUND,
    CATEGORY_INACTIVE,
    CATEGORY_ALREADY_EXISTS,
    INVALID_COORDINATES,
    INVALID_RADIUS,

    // Offers
    OFFER_NOT_FOUND,
    OFFER_ACCESS_DENIED,
    INVALID_OFFER_STATE,
    INVALID_OFFER_DATES,
    INVALID_OFFER_VALUE,
    INVALID_OFFER_TYPE,
    STORE_NOT_ELIGIBLE,

    // Payment & Transaction
    OFFER_NOT_ELIGIBLE,
    PAYMENT_NOT_FOUND,
    PAYMENT_ACCESS_DENIED,
    IDEMPOTENCY_CONFLICT,
    INVALID_PAYMENT_STATE,
    PAYMENT_CANCEL_FAILED,
    INVALID_CURRENCY,
    TRANSACTION_NOT_FOUND,
    TRANSACTION_ACCESS_DENIED,
    WEBHOOK_SIGNATURE_INVALID,
    PAYMENT_PROVIDER_ERROR,

    // Redemption
    PAYMENT_NOT_SUCCESSFUL,
    OFFER_ALREADY_REDEEMED,
    OFFER_EXPIRED,
    OFFER_USAGE_LIMIT_REACHED,
    CUSTOMER_OFFER_LIMIT_REACHED,
    REDEMPTION_NOT_FOUND,
    REDEMPTION_ACCESS_DENIED,

    // Password
    CURRENT_PASSWORD_INCORRECT,
    PASSWORD_RESET_OTP_INVALID,
    PASSWORD_RESET_OTP_EXPIRED,
    PASSWORD_RESET_OTP_USED,
    PASSWORD_RESET_TOO_MANY_ATTEMPTS,
    WEAK_PASSWORD,

    // Rate limiting
    RATE_LIMIT_EXCEEDED,

    // Validation
    VALIDATION_FAILED,
    VALIDATION_ERROR,

    // General
    RESOURCE_NOT_FOUND,
    DUPLICATE_RESOURCE,
    INTERNAL_SERVER_ERROR,
    SERVICE_UNAVAILABLE
}
